export const REQUEST_TRIVIA = 'REQUEST_TRIVIA';
export const RECEIVE_TRIVIA_SUCCESS = 'RECEIVE_TRIVIA_SUCCESS';
export const RECEIVE_TRIVIA_FAILURE = 'RECEIVE_TRIVIA_FAILURE';
export const RESET_TRIVIA = 'RESET_TRIVIA';
export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
