export const REQUEST_THEMEALAPI = 'REQUEST_THEMEALAPI';
export const RECEIVE_THEMEALAPI_SUCCESS = 'RECEIVE_THEMEALAPI_SUCCESS';
export const RECEIVE_THEMEALAPI_FAILURE = 'RECEIVE_THEMEALAPI_FAILURE';
export const REQUEST_RESET_FETCH_STATE = 'REQUEST_RESET_FETCH_STATE';
export const REQUEST_RESET_RECIPES_STATE = 'REQUEST_RESET_RECIPES_STATE';
export const FETCH_BY_INGREDIENT = 'FETCH_BY_INGREDIENT';
export const CHANGE_FETCH_BY_INGREDIENT = 'CHANGE_FETCH_BY_INGREDIENT';
